#!/usr/bin/env python3

import sys, subprocess, re

def parse():
    pgm = []
    for line in sys.stdin:
        pgm.append('P2\n96 96\n255\n' + line.rpartition(',')[2])
    return pgm

h = sys.stdin.readline().strip()
if h == 'ImageId,Image' or h.startswith('left_eye_center_x,left_eye_center_y,'):
    pgm = parse()
    nr = 0
    for file in pgm:
        nr += 1
        p = subprocess.Popen(['convert', '-', str(nr) + '.png'], stdin=subprocess.PIPE, universal_newlines=True)
        p.communicate(file)
else:
    print('Invalid input')
    exit()
